language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - nightly

install:
  - pip install coveralls
  - python setup.py install

script: coverage run --source=haikunator/haikunator.py setup.py test

after_success: coveralls
